//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnisensViewer.Translations {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnisensViewer.Translations.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Both ähnelt.
        /// </summary>
        internal static string AbsoluteDauerZeit {
            get {
                return ResourceManager.GetString("AbsoluteDauerZeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Absolute time ähnelt.
        /// </summary>
        internal static string AbsoluteUhrzeit {
            get {
                return ResourceManager.GetString("AbsoluteUhrzeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        internal static string Alles {
            get {
                return ResourceManager.GetString("Alles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close all ähnelt.
        /// </summary>
        internal static string Alleschließen {
            get {
                return ResourceManager.GetString("Alleschließen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close all ähnelt.
        /// </summary>
        internal static string Alleschließen1 {
            get {
                return ResourceManager.GetString("Alleschließen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die movisens ähnelt.
        /// </summary>
        internal static string Analyze {
            get {
                return ResourceManager.GetString("Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analyze File ähnelt.
        /// </summary>
        internal static string AnalyzeFile {
            get {
                return ResourceManager.GetString("AnalyzeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annotations ähnelt.
        /// </summary>
        internal static string Annotations {
            get {
                return ResourceManager.GetString("Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        internal static string Ansicht {
            get {
                return ResourceManager.GetString("Ansicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marks the selected area as artifact ähnelt.
        /// </summary>
        internal static string ArtifactsDescription {
            get {
                return ResourceManager.GetString("ArtifactsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark Artifact ähnelt.
        /// </summary>
        internal static string ArtifactsLabel {
            get {
                return ResourceManager.GetString("ArtifactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection ähnelt.
        /// </summary>
        internal static string Auswahl {
            get {
                return ResourceManager.GetString("Auswahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string Beenden {
            get {
                return ResourceManager.GetString("Beenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Region ähnelt.
        /// </summary>
        internal static string Bereich {
            get {
                return ResourceManager.GetString("Bereich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment: ähnelt.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free text comments for this Entry ähnelt.
        /// </summary>
        internal static string CommentToolTip {
            get {
                return ResourceManager.GetString("CommentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crops signals to the selected time interval. ähnelt.
        /// </summary>
        internal static string CropDescription {
            get {
                return ResourceManager.GetString("CropDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crop to Selection ähnelt.
        /// </summary>
        internal static string CropLabel {
            get {
                return ResourceManager.GetString("CropLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cursor Data ähnelt.
        /// </summary>
        internal static string CursorData {
            get {
                return ResourceManager.GetString("CursorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string Datei {
            get {
                return ResourceManager.GetString("Datei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration: ähnelt.
        /// </summary>
        internal static string Dauer {
            get {
                return ResourceManager.GetString("Dauer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration of the measurement ähnelt.
        /// </summary>
        internal static string DauerBeginMessung {
            get {
                return ResourceManager.GetString("DauerBeginMessung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        internal static string Drucken {
            get {
                return ResourceManager.GetString("Drucken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit signals ähnelt.
        /// </summary>
        internal static string EditSignals {
            get {
                return ResourceManager.GetString("EditSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single value visualization ähnelt.
        /// </summary>
        internal static string EinzelwerteDarstellung {
            get {
                return ResourceManager.GetString("EinzelwerteDarstellung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End: ähnelt.
        /// </summary>
        internal static string Ende {
            get {
                return ResourceManager.GetString("Ende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entry-ID (filename) of the new marker list  ähnelt.
        /// </summary>
        internal static string EntryIdToolTip {
            get {
                return ResourceManager.GetString("EntryIdToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a file name that contains only letters, numbers and the character &apos;-&apos;, &apos;_&apos; and &apos;.&apos;. Example: Dateiname_01 ähnelt.
        /// </summary>
        internal static string EntryIdWarning {
            get {
                return ResourceManager.GetString("EntryIdWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expert mode ähnelt.
        /// </summary>
        internal static string Expertenmodus {
            get {
                return ResourceManager.GetString("Expertenmodus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crosshair ähnelt.
        /// </summary>
        internal static string Fadenkreuz {
            get {
                return ResourceManager.GetString("Fadenkreuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crosshair ähnelt.
        /// </summary>
        internal static string Fadenkreuz1 {
            get {
                return ResourceManager.GetString("Fadenkreuz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback and Bug-Report ähnelt.
        /// </summary>
        internal static string FeedbackundBugReport {
            get {
                return ResourceManager.GetString("FeedbackundBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File &quot;%filename%&quot; not found. ähnelt.
        /// </summary>
        internal static string FileNotFoundMsg {
            get {
                return ResourceManager.GetString("FileNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File not found ähnelt.
        /// </summary>
        internal static string FileNotFoundTitle {
            get {
                return ResourceManager.GetString("FileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequency: ähnelt.
        /// </summary>
        internal static string Frequenz {
            get {
                return ResourceManager.GetString("Frequenz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string Hilfe {
            get {
                return ResourceManager.GetString("Hilfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string Hilfe1 {
            get {
                return ResourceManager.GetString("Hilfe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Homepage ähnelt.
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Homepage ähnelt.
        /// </summary>
        internal static string Homepage1 {
            get {
                return ResourceManager.GetString("Homepage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index: ähnelt.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Individual ähnelt.
        /// </summary>
        internal static string Individuell {
            get {
                return ResourceManager.GetString("Individuell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input Errors ähnelt.
        /// </summary>
        internal static string InputErrors {
            get {
                return ResourceManager.GetString("InputErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interpolation ähnelt.
        /// </summary>
        internal static string Interpolation {
            get {
                return ResourceManager.GetString("Interpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interpolation ähnelt.
        /// </summary>
        internal static string Interpolation1 {
            get {
                return ResourceManager.GetString("Interpolation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compression ähnelt.
        /// </summary>
        internal static string Kompression {
            get {
                return ResourceManager.GetString("Kompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compression ähnelt.
        /// </summary>
        internal static string Kompression1 {
            get {
                return ResourceManager.GetString("Kompression1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compress the visualized data with a min/max compression ähnelt.
        /// </summary>
        internal static string KomprimiertdieangezeigtenDate {
            get {
                return ResourceManager.GetString("KomprimiertdieangezeigtenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact ähnelt.
        /// </summary>
        internal static string Kontakt {
            get {
                return ResourceManager.GetString("Kontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Event ähnelt.
        /// </summary>
        internal static string LetztesEvent {
            get {
                return ResourceManager.GetString("LetztesEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linear ähnelt.
        /// </summary>
        internal static string Linear {
            get {
                return ResourceManager.GetString("Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linear ähnelt.
        /// </summary>
        internal static string Linear1 {
            get {
                return ResourceManager.GetString("Linear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets a marker. Use key d to delete the marker in the selected interval. ähnelt.
        /// </summary>
        internal static string MarkerDescription {
            get {
                return ResourceManager.GetString("MarkerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marker ähnelt.
        /// </summary>
        internal static string MarkerLabel {
            get {
                return ResourceManager.GetString("MarkerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new EventEntry to save a list of markers ähnelt.
        /// </summary>
        internal static string MarkerListDescription {
            get {
                return ResourceManager.GetString("MarkerListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create marker list ähnelt.
        /// </summary>
        internal static string MarkerListLabel {
            get {
                return ResourceManager.GetString("MarkerListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marker list separated by a semicolon (;) ähnelt.
        /// </summary>
        internal static string MarkerListToolTip {
            get {
                return ResourceManager.GetString("MarkerListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The markers must contain an integer in the first column and may contain up to three columns. The columns are separated by a semicolon &apos;;&apos;. Example: 10;M;Marker. ähnelt.
        /// </summary>
        internal static string MarkerListWarning {
            get {
                return ResourceManager.GetString("MarkerListWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minute ähnelt.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grouped by files ähnelt.
        /// </summary>
        internal static string NachDateiengruppiert {
            get {
                return ResourceManager.GetString("NachDateiengruppiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grouped by unit ähnelt.
        /// </summary>
        internal static string NachEinheitengruppiert {
            get {
                return ResourceManager.GetString("NachEinheitengruppiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for updates ähnelt.
        /// </summary>
        internal static string NachUpdatessuchen {
            get {
                return ResourceManager.GetString("NachUpdatessuchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        internal static string Neu {
            get {
                return ResourceManager.GetString("Neu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates a new group with the selected entries ähnelt.
        /// </summary>
        internal static string NewGroupDescription {
            get {
                return ResourceManager.GetString("NewGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Group ähnelt.
        /// </summary>
        internal static string NewGroupLabel {
            get {
                return ResourceManager.GetString("NewGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        internal static string Öffnen {
            get {
                return ResourceManager.GetString("Öffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Physical: ähnelt.
        /// </summary>
        internal static string Physikalisch {
            get {
                return ResourceManager.GetString("Physikalisch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Round physical value ähnelt.
        /// </summary>
        internal static string PhysikalischenWertrunden {
            get {
                return ResourceManager.GetString("PhysikalischenWertrunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Round physical value ähnelt.
        /// </summary>
        internal static string PhysikalischenWertrunden1 {
            get {
                return ResourceManager.GetString("PhysikalischenWertrunden1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plug-ins ähnelt.
        /// </summary>
        internal static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Point ähnelt.
        /// </summary>
        internal static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Point ähnelt.
        /// </summary>
        internal static string Point1 {
            get {
                return ResourceManager.GetString("Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position: ähnelt.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rounding accuracy: ähnelt.
        /// </summary>
        internal static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rounds the physical value in the Cursor-Data-View to 4 decimal places ähnelt.
        /// </summary>
        internal static string RundetdenphysikalischenWertind {
            get {
                return ResourceManager.GetString("RundetdenphysikalischenWertind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10 Seconds ähnelt.
        /// </summary>
        internal static string S10Sekunden {
            get {
                return ResourceManager.GetString("S10Sekunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unscaled: ähnelt.
        /// </summary>
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sample and Hold ähnelt.
        /// </summary>
        internal static string SampleAndHold {
            get {
                return ResourceManager.GetString("SampleAndHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sample and Hold ähnelt.
        /// </summary>
        internal static string SampleandHold1 {
            get {
                return ResourceManager.GetString("SampleandHold1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling rate [Hz]: ähnelt.
        /// </summary>
        internal static string Sampling {
            get {
                return ResourceManager.GetString("Sampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling rate in Hz ähnelt.
        /// </summary>
        internal static string SamplingToolTip {
            get {
                return ResourceManager.GetString("SamplingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sampling rate must be a number (example: 25,6). ähnelt.
        /// </summary>
        internal static string SamplingWarning {
            get {
                return ResourceManager.GetString("SamplingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables/Disables the Crosshair ähnelt.
        /// </summary>
        internal static string SchaltenFadenkreuzanundab {
            get {
                return ResourceManager.GetString("SchaltenFadenkreuzanundab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables/Disables the linear visualization ähnelt.
        /// </summary>
        internal static string SchaltenVisualizationLinearanu {
            get {
                return ResourceManager.GetString("SchaltenVisualizationLinearanu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables/Disables the point visualization ähnelt.
        /// </summary>
        internal static string SchaltenVisualizationPointanun {
            get {
                return ResourceManager.GetString("SchaltenVisualizationPointanun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables/Disables the sample and hold visualization ähnelt.
        /// </summary>
        internal static string SchaltenVisualizationSampleAnd {
            get {
                return ResourceManager.GetString("SchaltenVisualizationSampleAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string Schließen {
            get {
                return ResourceManager.GetString("Schließen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closes all open signals ähnelt.
        /// </summary>
        internal static string SchließtallegeöffnetenSignale {
            get {
                return ResourceManager.GetString("SchließtallegeöffnetenSignale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Screenshot ähnelt.
        /// </summary>
        internal static string Screenshotexportieren {
            get {
                return ResourceManager.GetString("Screenshotexportieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service ähnelt.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal visualization ähnelt.
        /// </summary>
        internal static string Signale {
            get {
                return ResourceManager.GetString("Signale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale Signals ähnelt.
        /// </summary>
        internal static string SignaleSkalieren {
            get {
                return ResourceManager.GetString("SignaleSkalieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale ähnelt.
        /// </summary>
        internal static string SignaleSkalierenButton {
            get {
                return ResourceManager.GetString("SignaleSkalierenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sinc-Interpolation der angezeigten Signale ähnelt.
        /// </summary>
        internal static string SincInterpolationderangezeigte {
            get {
                return ResourceManager.GetString("SincInterpolationderangezeigte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Speichern {
            get {
                return ResourceManager.GetString("Speichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save As ähnelt.
        /// </summary>
        internal static string Speichernunter {
            get {
                return ResourceManager.GetString("Speichernunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start: ähnelt.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hour ähnelt.
        /// </summary>
        internal static string Stunde {
            get {
                return ResourceManager.GetString("Stunde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System language ähnelt.
        /// </summary>
        internal static string SystemLanguage {
            get {
                return ResourceManager.GetString("SystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days ähnelt.
        /// </summary>
        internal static string Tage {
            get {
                return ResourceManager.GetString("Tage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete at the begin or end of a signal the selected time interval. ähnelt.
        /// </summary>
        internal static string TrimDescription {
            get {
                return ResourceManager.GetString("TrimDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trim Start/End ähnelt.
        /// </summary>
        internal static string TrimLabel {
            get {
                return ResourceManager.GetString("TrimLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About UnisensViewer ähnelt.
        /// </summary>
        internal static string ÜberUnisensViewer {
            get {
                return ResourceManager.GetString("ÜberUnisensViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time: ähnelt.
        /// </summary>
        internal static string Uhrzeit {
            get {
                return ResourceManager.GetString("Uhrzeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time: ähnelt.
        /// </summary>
        internal static string Uhrzeit1 {
            get {
                return ResourceManager.GetString("Uhrzeit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time: ähnelt.
        /// </summary>
        internal static string Uhrzeit2 {
            get {
                return ResourceManager.GetString("Uhrzeit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unisens ähnelt.
        /// </summary>
        internal static string Unisens {
            get {
                return ResourceManager.GetString("Unisens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure Updates ähnelt.
        /// </summary>
        internal static string Updateskonfigurieren {
            get {
                return ResourceManager.GetString("Updateskonfigurieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visualization ähnelt.
        /// </summary>
        internal static string Visualisierung {
            get {
                return ResourceManager.GetString("Visualisierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        internal static string Wert {
            get {
                return ResourceManager.GetString("Wert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        internal static string Wert1 {
            get {
                return ResourceManager.GetString("Wert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Week ähnelt.
        /// </summary>
        internal static string Woche {
            get {
                return ResourceManager.GetString("Woche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        internal static string Zeit {
            get {
                return ResourceManager.GetString("Zeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        internal static string Zeit1 {
            get {
                return ResourceManager.GetString("Zeit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        internal static string Zeit2 {
            get {
                return ResourceManager.GetString("Zeit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format of Time ähnelt.
        /// </summary>
        internal static string ZeitFormat {
            get {
                return ResourceManager.GetString("ZeitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale Time ähnelt.
        /// </summary>
        internal static string ZeitSkalieren {
            get {
                return ResourceManager.GetString("ZeitSkalieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die last opened datasets . . . ähnelt.
        /// </summary>
        internal static string zuletztgeöffneteDatensätze {
            get {
                return ResourceManager.GetString("zuletztgeöffneteDatensätze", resourceCulture);
            }
        }
    }
}
